# Generated by Django 5.0.6 on 2024-06-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre_demande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedemploi',
            name='date_soumission',
            field=models.DateTimeField(),
        ),
    ]
